name: Deploy Ilmenauer Schachverein

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date
        run: echo "DATETIME=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo site
        run: |
          go run rangliste.go
          go run paarungen.go 
          hugo mod get
          hugo mod tidy
          hugo

      - name: Deploy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          source: "public/*"
          target: "/var/www/vm"
          rm: true
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Create folder structure
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd /var/www/vm; mv public/* .;  rm -rf public

      - name: PHP Composer
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/vm/register
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); exit(1); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            rm composer-setup.php
            composer install
            composer show
            suggests=$(composer suggests | grep -oE "^[^ ]+")
            for package in $suggests; do
                echo "Installing suggested package: $package"
                composer require "$package"
            done
