name: Mirror to GitLab

on:
  push:
    branches:
      - '**'  

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: Mirror to GitLab (with rebase)
        run: |
          git remote add gitlab "https://oauth2:${PAT}@gitlab.erik-skopp.de/ilmenauerschachverein/turniere/vereinsmeisterschaft.git"
          git fetch gitlab
          git rebase gitlab/main || echo "No changes to rebase"
          git push gitlab --all
          git push gitlab --tags