name: Mirror to GitLab

on:
  push:
    branches:
      - '**'  

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: Push to GitLab mirror
        run: |
          git remote add gitlab https://oauth2:${{ secrets.PAT }}@gitlab.erik-skopp.de/ilmenauerschachverein/turniere/vereinsmeisterschaft.git
          git push --mirror gitlab
