name: Convert Tables

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  convert_tables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' 

      - name: Run table conversion script
        run: go run table.go

      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Überprüfe, ob Änderungen vorhanden sind
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Automated table conversion"
            git push
          else
            echo "No changes to commit."
          fi
